n_1 = int(input("Entrer un nombre A:"))
n_2 = int(input("Entrer un nombre B:"))
n_3 = int(input("Entrer un nombre C:"))

n=min(n_1,n_2,n_3)

print(n)

def caractere(mot):
    for i in mot:
        print(i)

jean = str(input("entrer un mot:"))
caractere(jean)

def somme(n):
    n=n*1,27
    return n

n_1 = int(input("Veuillez entrer une somme :"))
somme(n_1)
print(somme(n_1))



Salaire = 500000

while Salaire < 1000000:
    
    Salaire += 200
    print( "Votre salaire est de:", Salaire, "Fcfa")

nombre_abonne = 250

mois = 0

while mois <= 24:

    nombre_abonne *= 1.10

    print("Vous avez actuellement{} abonnés !".format(nombre_abonne))

    mois += 1


    






































































































 

    